### ISSUE TITLE
Error in Shrink or Enlarge Token Size

### ISSUE THREAD

**Issue by Gjjring** [foundry-vtt-community/macros#334]
Output from console:

Error: You are accessing PlaceableObject#data which is no longer used and instead the Document class should be referenced directly as PlaceableObject#document.
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at Token5e.get (foundry.js:24741:23)
    at Macro.eval (eval at _executeScript (foundry.js:20000:16), <anonymous>:7:50)
    at Macro._executeScript (foundry.js:20002:17)
    at Macro.execute (foundry.js:19957:21)
    at Hotbar._onClickMacro (foundry.js:68047:20)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Comment by Broadway-afk** [comment]
"data" is outdated field now for a many of foundry models, so you should just inspect parent of data field with browser console and figure out new field responsible for token size.
